### ISSUE TITLE
use release tags directly here (git) instead of pling

### ISSUE THREAD

**Issue by pc00per** [xiaomi-sdm678/android_kernel_xiaomi_mojito#2]
Real issue is XDA being cheesy over pling links. No one being able to use WCSF kernel download links on XDA due to this. 
It's better to release tags with kernel attachments directly over here, like how cyberknight777 does with NetErnels.

**Comment by Anush02198** [comment]
https://forum.xda-developers.com/t/xda-rule-13-pling.4403549/

Its allowed to post on XDA

**Comment by pc00per** [comment]
> https://forum.xda-developers.com/t/xda-rule-13-pling.4403549/
> 
> Its allowed to post on XDA

Welp, you gotta tell this to mojito forum moderator. They're still removing pling links / threads. Even your own kernel XDA thread doesn't exist.

Moreover, I donno why you seem to be hesitant to release tags directly on the source page.

**Comment by TejasKamat** [comment]
> > https://forum.xda-developers.com/t/xda-rule-13-pling.4403549/
> > Its allowed to post on XDA
> 
> Welp, you gotta tell this to mojito forum moderator. They're still removing pling links / threads. Even your own kernel XDA thread doesn't exist.
> 
> Moreover, I donno why you seem to be hesitant to release tags directly on the source page.

You absolutely made no sense my man, ofcourse it's clear he wants per download revinue to keep the development free and i see nothing wrong in this. And even I believe in maintaining own business instead of inserting nose in other's business. Thanks
